version: '3'
services:
  amqp-broker:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
  ocpp-db:
    image: citrineos/postgis:v1.1.0
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: citrine
      POSTGRES_USER: citrine
      POSTGRES_PASSWORD: "citrine"
    healthcheck:
      test: "pg_isready --username=citrine"
      interval: 5s
      timeout: 10s
      retries: 5
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  jaeger:
    image: jaegertracing/all-in-one:1.55
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14269:14269
      - 14250:14250
      - 9411:9411
      - 4317:4317
      - 4318:4318
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
  citrine:
    build:
      context: ..
      dockerfile: ./Server/local.Dockerfile
    volumes:
      - ../:/usr/local/apps/citrineos
      - /usr/local/apps/citrineos/node_modules
      - /usr/local/apps/citrineos/Server/node_modules
      - /usr/local/apps/citrineos/00_Base/node_modules
      - /usr/local/apps/citrineos/01_Data/node_modules
      - /usr/local/apps/citrineos/02_Util/node_modules
      - /usr/local/apps/citrineos/03_Modules/Certificates/node_modules
      - /usr/local/apps/citrineos/03_Modules/Configuration/node_modules
      - /usr/local/apps/citrineos/03_Modules/EVDriver/node_modules
      - /usr/local/apps/citrineos/03_Modules/Monitoring/node_modules
      - /usr/local/apps/citrineos/03_Modules/OcppRouter/node_modules
      - /usr/local/apps/citrineos/03_Modules/Reporting/node_modules
      - /usr/local/apps/citrineos/03_Modules/SmartCharging/node_modules
      - /usr/local/apps/citrineos/03_Modules/Transactions/node_modules
      - /usr/local/apps/citrineos/dist/
      - /usr/local/apps/citrineos/Server/dist/
      - /usr/local/apps/citrineos/00_Base/dist/
      - /usr/local/apps/citrineos/01_Data/dist/
      - /usr/local/apps/citrineos/02_Util/dist/
      - /usr/local/apps/citrineos/03_Modules/Certificates/dist/
      - /usr/local/apps/citrineos/03_Modules/Configuration/dist/
      - /usr/local/apps/citrineos/03_Modules/EVDriver/dist/
      - /usr/local/apps/citrineos/03_Modules/Monitoring/dist/
      - /usr/local/apps/citrineos/03_Modules/OcppRouter/dist/
      - /usr/local/apps/citrineos/03_Modules/Reporting/dist/
      - /usr/local/apps/citrineos/03_Modules/SmartCharging/dist/
      - /usr/local/apps/citrineos/03_Modules/Transactions/dist/
    environment:
      APP_NAME: "all"
      APP_ENV: "docker"
      CITRINEOS_UTIL_DIRECTUS_USERNAME: 'admin@citrineos.com'
      CITRINEOS_UTIL_DIRECTUS_PASSWORD: 'CitrineOS!'
      JAEGER_URI: 'http://jaeger:4318'
    depends_on:
      ocpp-db:
        condition: service_started
      amqp-broker:
        condition: service_healthy
      directus:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 9229:9229
  directus:
    build:
      context: ..
      dockerfile: ./Server/directus.Dockerfile
    ports:
      - 8055:8055
    volumes:
      - ./data/directus/uploads:/directus/uploads
      - ./directus-env-config.cjs:/directus/config.cjs
    depends_on:
      ocpp-db:
        condition: service_healthy
    environment:
      APP_NAME: 'all'
      KEY: '1234567890'
      SECRET: '0987654321'
      ADMIN_EMAIL: 'admin@citrineos.com'
      ADMIN_PASSWORD: 'CitrineOS!'
      CONFIG_PATH: '/directus/config.cjs'
      EXTENSIONS_AUTO_RELOAD: 'true'
      EXTENSIONS_CACHE_TTL: '1s'
      DB_CLIENT: 'pg'
      DB_HOST: ocpp-db
      DB_PORT: 5432
      DB_DATABASE: 'citrine'
      DB_USER: 'citrine'
      DB_PASSWORD: 'citrine'
      WEBSOCKETS_ENABLED: 'true'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8055/server/health || exit 1
      start_period: 15s
      interval: 15s
      timeout: 15s
      retries: 3